"""add Department

Revision ID: 50898671e14e
Revises: c2d5ec686e65
Create Date: 2024-06-29 20:43:50.156327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50898671e14e'
down_revision = 'c2d5ec686e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
